# Generated by Django 4.2 on 2024-03-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_passenger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passenger",
            old_name="flight",
            new_name="flights",
        ),
    ]
